In [ ]:
%matplotlib inline
import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import pandas as pd
pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)
pd.set_option('display.notebook_repr_html', True)
import seaborn as sns
sns.set_style("whitegrid")
sns.set_context("poster")

In [ ]:
data_large=pd.read_csv('/content/drive/MyDrive/Project/Crime (18-p)/Crime - (18-p) 1_final.csv')

In [ ]:
data=data_large
data.shape
data.head(5)

,Unnamed: 0,Unnamed: 0.1,ID,Case Number,Date,Block,IUCR,Description,Arrest,Domestic,Beat,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,severe,Primary Type_ARSON,Primary Type_ASSAULT,Primary Type_BATTERY,Primary Type_BURGLARY,Primary Type_CONCEALED CARRY LICENSE VIOLATION,Primary Type_CRIM SEXUAL ASSAULT,Primary Type_CRIMINAL DAMAGE,Primary Type_CRIMINAL SEXUAL ASSAULT,Primary Type_CRIMINAL TRESPASS,Primary Type_DECEPTIVE PRACTICE,Primary Type_HOMICIDE,Primary Type_INTERFERENCE WITH PUBLIC OFFICER,Primary Type_INTIMIDATION,Primary Type_LIQUOR LAW VIOLATION,Primary Type_MOTOR VEHICLE THEFT,Primary Type_NARCOTICS,Primary Type_OFFENSE INVOLVING CHILDREN,Primary Type_PROSTITUTION,Primary Type_PUBLIC PEACE VIOLATION,Primary Type_ROBBERY,Primary Type_SEX OFFENSE,Primary Type_STALKING,Primary Type_THEFT,Primary Type_WEAPONS VIOLATION,District_D1,District_D10,District_D11,District_D12,...,District_D9,District,Primary Type,time_24hour,Date_no_time,Timeblock_0,Timeblock_12,Timeblock_15,Timeblock_18,Timeblock_21,Timeblock_3,Timeblock_6,Timeblock_9,Weekday_Friday,Weekday_Monday,Weekday_Saturday,Weekday_Sunday,Weekday_Thursday,Weekday_Tuesday,Weekday_Wednesday,closest_station,Income,HARDSHIP INDEX,Under18_over64,Unemployed,House_below_poverty,Location Description_ALLEY,Location Description_APARTMENT,Location Description_BAR OR TAVERN,Location Description_COMMERCIAL / BUSINESS OFFICE,Location Description_CONVENIENCE STORE,Location Description_CTA TRAIN,Location Description_DEPARTMENT STORE,Location Description_GAS STATION,Location Description_GROCERY FOOD STORE,Location Description_OTHER (SPECIFY),Location Description_PARKING LOT / GARAGE (NON RESIDENTIAL),Location Description_PARKING LOT/GARAGE(NON.RESID.),Location Description_RESIDENCE,Location Description_RESIDENCE - PORCH / HALLWAY,Location Description_RESIDENCE - YARD (FRONT / BACK),Location Description_RESIDENCE PORCH/HALLWAY,Location Description_RESIDENCE-GARAGE,Location Description_RESIDENTIAL YARD (FRONT/BACK),Location Description_RESTAURANT,"Location Description_SCHOOL, PUBLIC, BUILDING",Location Description_SIDEWALK,Location Description_SMALL RETAIL STORE,Location Description_STREET,Location Description_VEHICLE NON-COMMERCIAL
0,0,154,11458569,JB451615,09/25/2018 03:45:00 PM,068XX S WASHTENAW AVE,0560,SIMPLE,False,False,831,17.0,66.0,08A,1159554.0,1859215.0,2018,06/04/2019 04:01:14 PM,41.769400,-87.690706,"(41.769399886, -87.690705813)",1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,D8,ASSAULT,15:45,20180925,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.145603,13231,80.0,40.6,17.1,27.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,1,155,11492590,JB496541,10/30/2018 04:59:00 PM,040XX W 30TH ST,041A,AGGRAVATED: HANDGUN,True,False,1031,22.0,30.0,04B,1149760.0,1884400.0,2018,06/04/2019 04:01:14 PM,41.838706,-87.725954,"(41.838706452, -87.72595418)",1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,...,0,D10,BATTERY,16:59,20181030,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.535472,10402,96.0,33.8,15.8,30.7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,2,156,11514713,JB525811,11/23/2018 01:30:00 AM,059XX W IOWA ST,1753,SEX ASSLT OF CHILD BY FAM MBR,True,False,1511,29.0,25.0,02,1136588.0,1905390.0,2018,06/04/2019 04:01:14 PM,41.896551,-87.773788,"(41.896551396, -87.773787663)",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,...,0,D15,OFFENSE INVOLVING CHILDREN,01:30,20181123,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1.172747,15957,73.0,37.9,22.6,28.6,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,3,426,11203556,JB115393,01/13/2018 08:24:00 PM,017XX W COLUMBIA AVE,041A,AGGRAVATED - HANDGUN,False,False,2432,49.0,1.0,04B,1163373.0,1944877.0,2018,03/25/2020 03:45:43 PM,42.004384,-87.674296,"(42.004384227, -87.674295522)",1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,D24,BATTERY,20:24,20180113,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0.353593,23939,39.0,27.5,8.7,23.6,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,4,431,11230081,JB151031,02/13/2018 05:51:00 PM,015XX N KILDARE AVE,0334,ATTEMPT ARMED - KNIFE / CUTTING INSTRUMENT,False,False,2534,26.0,23.0,03,1147424.0,1910122.0,2018,03/25/2020 03:45:43 PM,41.909336,-87.733867,"(41.909335675, -87.733867034)",1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,...,0,D25,ROBBERY,17:51,20180213,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.750428,13781,85.0,38.0,17.3,33.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [ ]:
data=data.drop(['Unnamed: 0',	'Unnamed: 0.1'	] ,1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.

In [ ]:
data.head()

,ID,Case Number,Date,Block,IUCR,Description,Arrest,Domestic,Beat,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,severe,Primary Type_ARSON,Primary Type_ASSAULT,Primary Type_BATTERY,Primary Type_BURGLARY,Primary Type_CONCEALED CARRY LICENSE VIOLATION,Primary Type_CRIM SEXUAL ASSAULT,Primary Type_CRIMINAL DAMAGE,Primary Type_CRIMINAL SEXUAL ASSAULT,Primary Type_CRIMINAL TRESPASS,Primary Type_DECEPTIVE PRACTICE,Primary Type_HOMICIDE,Primary Type_INTERFERENCE WITH PUBLIC OFFICER,Primary Type_INTIMIDATION,Primary Type_LIQUOR LAW VIOLATION,Primary Type_MOTOR VEHICLE THEFT,Primary Type_NARCOTICS,Primary Type_OFFENSE INVOLVING CHILDREN,Primary Type_PROSTITUTION,Primary Type_PUBLIC PEACE VIOLATION,Primary Type_ROBBERY,Primary Type_SEX OFFENSE,Primary Type_STALKING,Primary Type_THEFT,Primary Type_WEAPONS VIOLATION,District_D1,District_D10,District_D11,District_D12,District_D14,District_D15,...,District_D9,District,Primary Type,time_24hour,Date_no_time,Timeblock_0,Timeblock_12,Timeblock_15,Timeblock_18,Timeblock_21,Timeblock_3,Timeblock_6,Timeblock_9,Weekday_Friday,Weekday_Monday,Weekday_Saturday,Weekday_Sunday,Weekday_Thursday,Weekday_Tuesday,Weekday_Wednesday,closest_station,Income,HARDSHIP INDEX,Under18_over64,Unemployed,House_below_poverty,Location Description_ALLEY,Location Description_APARTMENT,Location Description_BAR OR TAVERN,Location Description_COMMERCIAL / BUSINESS OFFICE,Location Description_CONVENIENCE STORE,Location Description_CTA TRAIN,Location Description_DEPARTMENT STORE,Location Description_GAS STATION,Location Description_GROCERY FOOD STORE,Location Description_OTHER (SPECIFY),Location Description_PARKING LOT / GARAGE (NON RESIDENTIAL),Location Description_PARKING LOT/GARAGE(NON.RESID.),Location Description_RESIDENCE,Location Description_RESIDENCE - PORCH / HALLWAY,Location Description_RESIDENCE - YARD (FRONT / BACK),Location Description_RESIDENCE PORCH/HALLWAY,Location Description_RESIDENCE-GARAGE,Location Description_RESIDENTIAL YARD (FRONT/BACK),Location Description_RESTAURANT,"Location Description_SCHOOL, PUBLIC, BUILDING",Location Description_SIDEWALK,Location Description_SMALL RETAIL STORE,Location Description_STREET,Location Description_VEHICLE NON-COMMERCIAL
0,11458569,JB451615,09/25/2018 03:45:00 PM,068XX S WASHTENAW AVE,0560,SIMPLE,False,False,831,17.0,66.0,08A,1159554.0,1859215.0,2018,06/04/2019 04:01:14 PM,41.769400,-87.690706,"(41.769399886, -87.690705813)",1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,D8,ASSAULT,15:45,20180925,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.145603,13231,80.0,40.6,17.1,27.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,11492590,JB496541,10/30/2018 04:59:00 PM,040XX W 30TH ST,041A,AGGRAVATED: HANDGUN,True,False,1031,22.0,30.0,04B,1149760.0,1884400.0,2018,06/04/2019 04:01:14 PM,41.838706,-87.725954,"(41.838706452, -87.72595418)",1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,...,0,D10,BATTERY,16:59,20181030,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.535472,10402,96.0,33.8,15.8,30.7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,11514713,JB525811,11/23/2018 01:30:00 AM,059XX W IOWA ST,1753,SEX ASSLT OF CHILD BY FAM MBR,True,False,1511,29.0,25.0,02,1136588.0,1905390.0,2018,06/04/2019 04:01:14 PM,41.896551,-87.773788,"(41.896551396, -87.773787663)",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,...,0,D15,OFFENSE INVOLVING CHILDREN,01:30,20181123,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1.172747,15957,73.0,37.9,22.6,28.6,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,11203556,JB115393,01/13/2018 08:24:00 PM,017XX W COLUMBIA AVE,041A,AGGRAVATED - HANDGUN,False,False,2432,49.0,1.0,04B,1163373.0,1944877.0,2018,03/25/2020 03:45:43 PM,42.004384,-87.674296,"(42.004384227, -87.674295522)",1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,D24,BATTERY,20:24,20180113,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0.353593,23939,39.0,27.5,8.7,23.6,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,11230081,JB151031,02/13/2018 05:51:00 PM,015XX N KILDARE AVE,0334,ATTEMPT ARMED - KNIFE / CUTTING INSTRUMENT,False,False,2534,26.0,23.0,03,1147424.0,1910122.0,2018,03/25/2020 03:45:43 PM,41.909336,-87.733867,"(41.909335675, -87.733867034)",1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,...,0,D25,ROBBERY,17:51,20180213,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.750428,13781,85.0,38.0,17.3,33.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [ ]:
data.reset_index(inplace=True)
data.head(5)

,index,ID,Case Number,Date,Block,IUCR,Description,Arrest,Domestic,Beat,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,severe,Primary Type_ARSON,Primary Type_ASSAULT,Primary Type_BATTERY,Primary Type_BURGLARY,Primary Type_CONCEALED CARRY LICENSE VIOLATION,Primary Type_CRIM SEXUAL ASSAULT,Primary Type_CRIMINAL DAMAGE,Primary Type_CRIMINAL SEXUAL ASSAULT,Primary Type_CRIMINAL TRESPASS,Primary Type_DECEPTIVE PRACTICE,Primary Type_HOMICIDE,Primary Type_INTERFERENCE WITH PUBLIC OFFICER,Primary Type_INTIMIDATION,Primary Type_LIQUOR LAW VIOLATION,Primary Type_MOTOR VEHICLE THEFT,Primary Type_NARCOTICS,Primary Type_OFFENSE INVOLVING CHILDREN,Primary Type_PROSTITUTION,Primary Type_PUBLIC PEACE VIOLATION,Primary Type_ROBBERY,Primary Type_SEX OFFENSE,Primary Type_STALKING,Primary Type_THEFT,Primary Type_WEAPONS VIOLATION,District_D1,District_D10,District_D11,District_D12,District_D14,...,District_D9,District,Primary Type,time_24hour,Date_no_time,Timeblock_0,Timeblock_12,Timeblock_15,Timeblock_18,Timeblock_21,Timeblock_3,Timeblock_6,Timeblock_9,Weekday_Friday,Weekday_Monday,Weekday_Saturday,Weekday_Sunday,Weekday_Thursday,Weekday_Tuesday,Weekday_Wednesday,closest_station,Income,HARDSHIP INDEX,Under18_over64,Unemployed,House_below_poverty,Location Description_ALLEY,Location Description_APARTMENT,Location Description_BAR OR TAVERN,Location Description_COMMERCIAL / BUSINESS OFFICE,Location Description_CONVENIENCE STORE,Location Description_CTA TRAIN,Location Description_DEPARTMENT STORE,Location Description_GAS STATION,Location Description_GROCERY FOOD STORE,Location Description_OTHER (SPECIFY),Location Description_PARKING LOT / GARAGE (NON RESIDENTIAL),Location Description_PARKING LOT/GARAGE(NON.RESID.),Location Description_RESIDENCE,Location Description_RESIDENCE - PORCH / HALLWAY,Location Description_RESIDENCE - YARD (FRONT / BACK),Location Description_RESIDENCE PORCH/HALLWAY,Location Description_RESIDENCE-GARAGE,Location Description_RESIDENTIAL YARD (FRONT/BACK),Location Description_RESTAURANT,"Location Description_SCHOOL, PUBLIC, BUILDING",Location Description_SIDEWALK,Location Description_SMALL RETAIL STORE,Location Description_STREET,Location Description_VEHICLE NON-COMMERCIAL
0,0,11458569,JB451615,09/25/2018 03:45:00 PM,068XX S WASHTENAW AVE,0560,SIMPLE,False,False,831,17.0,66.0,08A,1159554.0,1859215.0,2018,06/04/2019 04:01:14 PM,41.769400,-87.690706,"(41.769399886, -87.690705813)",1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,D8,ASSAULT,15:45,20180925,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.145603,13231,80.0,40.6,17.1,27.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,1,11492590,JB496541,10/30/2018 04:59:00 PM,040XX W 30TH ST,041A,AGGRAVATED: HANDGUN,True,False,1031,22.0,30.0,04B,1149760.0,1884400.0,2018,06/04/2019 04:01:14 PM,41.838706,-87.725954,"(41.838706452, -87.72595418)",1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,...,0,D10,BATTERY,16:59,20181030,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.535472,10402,96.0,33.8,15.8,30.7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,2,11514713,JB525811,11/23/2018 01:30:00 AM,059XX W IOWA ST,1753,SEX ASSLT OF CHILD BY FAM MBR,True,False,1511,29.0,25.0,02,1136588.0,1905390.0,2018,06/04/2019 04:01:14 PM,41.896551,-87.773788,"(41.896551396, -87.773787663)",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,...,0,D15,OFFENSE INVOLVING CHILDREN,01:30,20181123,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1.172747,15957,73.0,37.9,22.6,28.6,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,3,11203556,JB115393,01/13/2018 08:24:00 PM,017XX W COLUMBIA AVE,041A,AGGRAVATED - HANDGUN,False,False,2432,49.0,1.0,04B,1163373.0,1944877.0,2018,03/25/2020 03:45:43 PM,42.004384,-87.674296,"(42.004384227, -87.674295522)",1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,D24,BATTERY,20:24,20180113,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0.353593,23939,39.0,27.5,8.7,23.6,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,4,11230081,JB151031,02/13/2018 05:51:00 PM,015XX N KILDARE AVE,0334,ATTEMPT ARMED - KNIFE / CUTTING INSTRUMENT,False,False,2534,26.0,23.0,03,1147424.0,1910122.0,2018,03/25/2020 03:45:43 PM,41.909336,-87.733867,"(41.909335675, -87.733867034)",1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,...,0,D25,ROBBERY,17:51,20180213,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.750428,13781,85.0,38.0,17.3,33.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [ ]:
data=data.drop(["index"], axis=1)
data.head(5)

,ID,Case Number,Date,Block,IUCR,Description,Arrest,Domestic,Beat,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,severe,Primary Type_ARSON,Primary Type_ASSAULT,Primary Type_BATTERY,Primary Type_BURGLARY,Primary Type_CONCEALED CARRY LICENSE VIOLATION,Primary Type_CRIM SEXUAL ASSAULT,Primary Type_CRIMINAL DAMAGE,Primary Type_CRIMINAL SEXUAL ASSAULT,Primary Type_CRIMINAL TRESPASS,Primary Type_DECEPTIVE PRACTICE,Primary Type_HOMICIDE,Primary Type_INTERFERENCE WITH PUBLIC OFFICER,Primary Type_INTIMIDATION,Primary Type_LIQUOR LAW VIOLATION,Primary Type_MOTOR VEHICLE THEFT,Primary Type_NARCOTICS,Primary Type_OFFENSE INVOLVING CHILDREN,Primary Type_PROSTITUTION,Primary Type_PUBLIC PEACE VIOLATION,Primary Type_ROBBERY,Primary Type_SEX OFFENSE,Primary Type_STALKING,Primary Type_THEFT,Primary Type_WEAPONS VIOLATION,District_D1,District_D10,District_D11,District_D12,District_D14,District_D15,...,District_D9,District,Primary Type,time_24hour,Date_no_time,Timeblock_0,Timeblock_12,Timeblock_15,Timeblock_18,Timeblock_21,Timeblock_3,Timeblock_6,Timeblock_9,Weekday_Friday,Weekday_Monday,Weekday_Saturday,Weekday_Sunday,Weekday_Thursday,Weekday_Tuesday,Weekday_Wednesday,closest_station,Income,HARDSHIP INDEX,Under18_over64,Unemployed,House_below_poverty,Location Description_ALLEY,Location Description_APARTMENT,Location Description_BAR OR TAVERN,Location Description_COMMERCIAL / BUSINESS OFFICE,Location Description_CONVENIENCE STORE,Location Description_CTA TRAIN,Location Description_DEPARTMENT STORE,Location Description_GAS STATION,Location Description_GROCERY FOOD STORE,Location Description_OTHER (SPECIFY),Location Description_PARKING LOT / GARAGE (NON RESIDENTIAL),Location Description_PARKING LOT/GARAGE(NON.RESID.),Location Description_RESIDENCE,Location Description_RESIDENCE - PORCH / HALLWAY,Location Description_RESIDENCE - YARD (FRONT / BACK),Location Description_RESIDENCE PORCH/HALLWAY,Location Description_RESIDENCE-GARAGE,Location Description_RESIDENTIAL YARD (FRONT/BACK),Location Description_RESTAURANT,"Location Description_SCHOOL, PUBLIC, BUILDING",Location Description_SIDEWALK,Location Description_SMALL RETAIL STORE,Location Description_STREET,Location Description_VEHICLE NON-COMMERCIAL
0,11458569,JB451615,09/25/2018 03:45:00 PM,068XX S WASHTENAW AVE,0560,SIMPLE,False,False,831,17.0,66.0,08A,1159554.0,1859215.0,2018,06/04/2019 04:01:14 PM,41.769400,-87.690706,"(41.769399886, -87.690705813)",1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,D8,ASSAULT,15:45,20180925,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.145603,13231,80.0,40.6,17.1,27.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,11492590,JB496541,10/30/2018 04:59:00 PM,040XX W 30TH ST,041A,AGGRAVATED: HANDGUN,True,False,1031,22.0,30.0,04B,1149760.0,1884400.0,2018,06/04/2019 04:01:14 PM,41.838706,-87.725954,"(41.838706452, -87.72595418)",1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,...,0,D10,BATTERY,16:59,20181030,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.535472,10402,96.0,33.8,15.8,30.7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,11514713,JB525811,11/23/2018 01:30:00 AM,059XX W IOWA ST,1753,SEX ASSLT OF CHILD BY FAM MBR,True,False,1511,29.0,25.0,02,1136588.0,1905390.0,2018,06/04/2019 04:01:14 PM,41.896551,-87.773788,"(41.896551396, -87.773787663)",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,...,0,D15,OFFENSE INVOLVING CHILDREN,01:30,20181123,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1.172747,15957,73.0,37.9,22.6,28.6,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,11203556,JB115393,01/13/2018 08:24:00 PM,017XX W COLUMBIA AVE,041A,AGGRAVATED - HANDGUN,False,False,2432,49.0,1.0,04B,1163373.0,1944877.0,2018,03/25/2020 03:45:43 PM,42.004384,-87.674296,"(42.004384227, -87.674295522)",1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,D24,BATTERY,20:24,20180113,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0.353593,23939,39.0,27.5,8.7,23.6,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,11230081,JB151031,02/13/2018 05:51:00 PM,015XX N KILDARE AVE,0334,ATTEMPT ARMED - KNIFE / CUTTING INSTRUMENT,False,False,2534,26.0,23.0,03,1147424.0,1910122.0,2018,03/25/2020 03:45:43 PM,41.909336,-87.733867,"(41.909335675, -87.733867034)",1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,...,0,D25,ROBBERY,17:51,20180213,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.750428,13781,85.0,38.0,17.3,33.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [ ]:
data=data.drop(["ID","Date","Block","IUCR","Description","Ward","Community Area","FBI Code"], axis=1)
data=data.drop(["X Coordinate","Y Coordinate","Year","Location","District","Primary Type","time_24hour","Date_no_time"], axis=1)

In [ ]:
a=list(data.columns.values)
droplist=[]
for i in a:
    if i.startswith("Primary Type"):
        droplist.append(i)
data=data.drop(droplist, axis=1)

In [ ]:
from sklearn.model_selection import cross_validate

In [ ]:
from sklearn.model_selection import train_test_split
itrain, itest = train_test_split(range(data.shape[0]), train_size=0.7)

In [ ]:
mask=np.ones(data.shape[0], dtype='int')
mask[itrain]=1
mask[itest]=0
mask=(mask==1)

In [ ]:
data.shape
data.head(5)

,Case Number,Arrest,Domestic,Beat,Updated On,Latitude,Longitude,severe,District_D1,District_D10,District_D11,District_D12,District_D14,District_D15,District_D16,District_D17,District_D18,District_D19,District_D2,District_D20,District_D22,District_D24,District_D25,District_D3,District_D4,District_D5,District_D6,District_D7,District_D8,District_D9,Timeblock_0,Timeblock_12,Timeblock_15,Timeblock_18,Timeblock_21,Timeblock_3,Timeblock_6,Timeblock_9,Weekday_Friday,Weekday_Monday,Weekday_Saturday,Weekday_Sunday,Weekday_Thursday,Weekday_Tuesday,Weekday_Wednesday,closest_station,Income,HARDSHIP INDEX,Under18_over64,Unemployed,House_below_poverty,Location Description_ALLEY,Location Description_APARTMENT,Location Description_BAR OR TAVERN,Location Description_COMMERCIAL / BUSINESS OFFICE,Location Description_CONVENIENCE STORE,Location Description_CTA TRAIN,Location Description_DEPARTMENT STORE,Location Description_GAS STATION,Location Description_GROCERY FOOD STORE,Location Description_OTHER (SPECIFY),Location Description_PARKING LOT / GARAGE (NON RESIDENTIAL),Location Description_PARKING LOT/GARAGE(NON.RESID.),Location Description_RESIDENCE,Location Description_RESIDENCE - PORCH / HALLWAY,Location Description_RESIDENCE - YARD (FRONT / BACK),Location Description_RESIDENCE PORCH/HALLWAY,Location Description_RESIDENCE-GARAGE,Location Description_RESIDENTIAL YARD (FRONT/BACK),Location Description_RESTAURANT,"Location Description_SCHOOL, PUBLIC, BUILDING",Location Description_SIDEWALK,Location Description_SMALL RETAIL STORE,Location Description_STREET,Location Description_VEHICLE NON-COMMERCIAL
0,JB451615,False,False,831,06/04/2019 04:01:14 PM,41.769400,-87.690706,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.145603,13231,80.0,40.6,17.1,27.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,JB496541,True,False,1031,06/04/2019 04:01:14 PM,41.838706,-87.725954,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.535472,10402,96.0,33.8,15.8,30.7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,JB525811,True,False,1511,06/04/2019 04:01:14 PM,41.896551,-87.773788,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1.172747,15957,73.0,37.9,22.6,28.6,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,JB115393,False,False,2432,03/25/2020 03:45:43 PM,42.004384,-87.674296,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0.353593,23939,39.0,27.5,8.7,23.6,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,JB151031,False,False,2534,03/25/2020 03:45:43 PM,41.909336,-87.733867,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.750428,13781,85.0,38.0,17.3,33.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [ ]:
data=data.dropna()
np.nan_to_num(data)

array([['JB451615', False, False, ..., 0, 0, 0],
       ['JB496541', True, False, ..., 0, 0, 0],
       ['JB525811', True, False, ..., 0, 0, 0],
       ...,
       ['JF179791', False, True, ..., 0, 0, 0],
       ['JF179649', False, False, ..., 0, 0, 0],
       ['JF179224', False, False, ..., 0, 1, 0]], dtype=object)

In [ ]:
from sklearn.preprocessing import StandardScaler
#Standardize training set
data.loc[mask,STANDARDIZABLE]=StandardScaler().fit_transform(data.loc[mask,STANDARDIZABLE])
#Standardize test set
data.loc[~mask,STANDARDIZABLE]=StandardScaler().fit_transform(data.loc[~mask,STANDARDIZABLE])
data.head(5)

,Case Number,Arrest,Domestic,Beat,Updated On,Latitude,Longitude,severe,District_D1,District_D10,District_D11,District_D12,District_D14,District_D15,District_D16,District_D17,District_D18,District_D19,District_D2,District_D20,District_D22,District_D24,District_D25,District_D3,District_D4,District_D5,District_D6,District_D7,District_D8,District_D9,Timeblock_0,Timeblock_12,Timeblock_15,Timeblock_18,Timeblock_21,Timeblock_3,Timeblock_6,Timeblock_9,Weekday_Friday,Weekday_Monday,Weekday_Saturday,Weekday_Sunday,Weekday_Thursday,Weekday_Tuesday,Weekday_Wednesday,closest_station,Income,HARDSHIP INDEX,Under18_over64,Unemployed,House_below_poverty,Location Description_ALLEY,Location Description_APARTMENT,Location Description_BAR OR TAVERN,Location Description_COMMERCIAL / BUSINESS OFFICE,Location Description_CONVENIENCE STORE,Location Description_CTA TRAIN,Location Description_DEPARTMENT STORE,Location Description_GAS STATION,Location Description_GROCERY FOOD STORE,Location Description_OTHER (SPECIFY),Location Description_PARKING LOT / GARAGE (NON RESIDENTIAL),Location Description_PARKING LOT/GARAGE(NON.RESID.),Location Description_RESIDENCE,Location Description_RESIDENCE - PORCH / HALLWAY,Location Description_RESIDENCE - YARD (FRONT / BACK),Location Description_RESIDENCE PORCH/HALLWAY,Location Description_RESIDENCE-GARAGE,Location Description_RESIDENTIAL YARD (FRONT/BACK),Location Description_RESTAURANT,"Location Description_SCHOOL, PUBLIC, BUILDING",Location Description_SIDEWALK,Location Description_SMALL RETAIL STORE,Location Description_STREET,Location Description_VEHICLE NON-COMMERCIAL
0,JB451615,False,False,831,06/04/2019 04:01:14 PM,-0.836976,-0.370022,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,-0.126778,-0.685590,0.889544,0.704885,0.040531,0.314167,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,JB496541,True,False,1031,06/04/2019 04:01:14 PM,-0.034840,-0.968052,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.286865,-0.831046,1.420269,-0.108688,-0.124920,0.590222,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,JB525811,True,False,1511,06/04/2019 04:01:14 PM,0.636591,-1.812838,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,-0.085135,-0.546144,0.658469,0.381380,0.745965,0.382156,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,JB115393,False,False,2432,03/25/2020 03:45:43 PM,1.886273,-0.085038,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,-1.341862,-0.137831,-0.463896,-0.864715,-1.036858,-0.103482,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,JB151031,False,False,2534,03/25/2020 03:45:43 PM,0.784749,-1.119568,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.801130,-0.657456,1.054597,0.393362,0.066184,0.896932,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [ ]:
from sklearn.ensemble import RandomForestClassifier
randf=RandomForestClassifier()
clfrdf, Xtrain, ytrain, Xtest, ytest, confrdf, training_accuracy, test_accuracy=do_classify(randf, {"n_estimators":[10, 20, 20, 50, 100]}, data, total_features, u'severe',1, mask=mask)
confusion_dict["Random forest"]=confrdf
model_dict["Random forest"]=clfrdf
accuracy_dict["Random forest"]=training_accuracy
accuracy_dict1["Random forest"]=test_accuracy

Training accuracy: 1.00
Test accuracy:     0.60
[[7403 4724]
 [4765 7108]]
RandomForestClassifier()