In [ ]:
%matplotlib inline
import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import pandas as pd
pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)
pd.set_option('display.notebook_repr_html', True)
import seaborn as sns
sns.set_style("whitegrid")
sns.set_context("poster")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data_large=pd.read_csv('/content/drive/MyDrive/Project/Crime (18-p)/Crime - (18-p) 1_final.csv')

In [ ]:
data=data_large
data.shape
data.head(5)

,Unnamed: 0,Unnamed: 0.1,ID,Case Number,Date,Block,IUCR,Description,Arrest,Domestic,Beat,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,severe,Primary Type_ARSON,Primary Type_ASSAULT,Primary Type_BATTERY,Primary Type_BURGLARY,Primary Type_CONCEALED CARRY LICENSE VIOLATION,Primary Type_CRIM SEXUAL ASSAULT,Primary Type_CRIMINAL DAMAGE,Primary Type_CRIMINAL SEXUAL ASSAULT,Primary Type_CRIMINAL TRESPASS,Primary Type_DECEPTIVE PRACTICE,Primary Type_HOMICIDE,Primary Type_INTERFERENCE WITH PUBLIC OFFICER,Primary Type_INTIMIDATION,Primary Type_LIQUOR LAW VIOLATION,Primary Type_MOTOR VEHICLE THEFT,Primary Type_NARCOTICS,Primary Type_OFFENSE INVOLVING CHILDREN,Primary Type_PROSTITUTION,Primary Type_PUBLIC PEACE VIOLATION,Primary Type_ROBBERY,Primary Type_SEX OFFENSE,Primary Type_STALKING,Primary Type_THEFT,Primary Type_WEAPONS VIOLATION,District_D1,District_D10,District_D11,District_D12,...,District_D9,District,Primary Type,time_24hour,Date_no_time,Timeblock_0,Timeblock_12,Timeblock_15,Timeblock_18,Timeblock_21,Timeblock_3,Timeblock_6,Timeblock_9,Weekday_Friday,Weekday_Monday,Weekday_Saturday,Weekday_Sunday,Weekday_Thursday,Weekday_Tuesday,Weekday_Wednesday,closest_station,Income,HARDSHIP INDEX,Under18_over64,Unemployed,House_below_poverty,Location Description_ALLEY,Location Description_APARTMENT,Location Description_BAR OR TAVERN,Location Description_COMMERCIAL / BUSINESS OFFICE,Location Description_CONVENIENCE STORE,Location Description_CTA TRAIN,Location Description_DEPARTMENT STORE,Location Description_GAS STATION,Location Description_GROCERY FOOD STORE,Location Description_OTHER (SPECIFY),Location Description_PARKING LOT / GARAGE (NON RESIDENTIAL),Location Description_PARKING LOT/GARAGE(NON.RESID.),Location Description_RESIDENCE,Location Description_RESIDENCE - PORCH / HALLWAY,Location Description_RESIDENCE - YARD (FRONT / BACK),Location Description_RESIDENCE PORCH/HALLWAY,Location Description_RESIDENCE-GARAGE,Location Description_RESIDENTIAL YARD (FRONT/BACK),Location Description_RESTAURANT,"Location Description_SCHOOL, PUBLIC, BUILDING",Location Description_SIDEWALK,Location Description_SMALL RETAIL STORE,Location Description_STREET,Location Description_VEHICLE NON-COMMERCIAL
0,0,154,11458569,JB451615,09/25/2018 03:45:00 PM,068XX S WASHTENAW AVE,0560,SIMPLE,False,False,831,17.0,66.0,08A,1159554.0,1859215.0,2018,06/04/2019 04:01:14 PM,41.769400,-87.690706,"(41.769399886, -87.690705813)",1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,D8,ASSAULT,15:45,20180925,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.145603,13231,80.0,40.6,17.1,27.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,1,155,11492590,JB496541,10/30/2018 04:59:00 PM,040XX W 30TH ST,041A,AGGRAVATED: HANDGUN,True,False,1031,22.0,30.0,04B,1149760.0,1884400.0,2018,06/04/2019 04:01:14 PM,41.838706,-87.725954,"(41.838706452, -87.72595418)",1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,...,0,D10,BATTERY,16:59,20181030,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.535472,10402,96.0,33.8,15.8,30.7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,2,156,11514713,JB525811,11/23/2018 01:30:00 AM,059XX W IOWA ST,1753,SEX ASSLT OF CHILD BY FAM MBR,True,False,1511,29.0,25.0,02,1136588.0,1905390.0,2018,06/04/2019 04:01:14 PM,41.896551,-87.773788,"(41.896551396, -87.773787663)",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,...,0,D15,OFFENSE INVOLVING CHILDREN,01:30,20181123,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1.172747,15957,73.0,37.9,22.6,28.6,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,3,426,11203556,JB115393,01/13/2018 08:24:00 PM,017XX W COLUMBIA AVE,041A,AGGRAVATED - HANDGUN,False,False,2432,49.0,1.0,04B,1163373.0,1944877.0,2018,03/25/2020 03:45:43 PM,42.004384,-87.674296,"(42.004384227, -87.674295522)",1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,D24,BATTERY,20:24,20180113,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0.353593,23939,39.0,27.5,8.7,23.6,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,4,431,11230081,JB151031,02/13/2018 05:51:00 PM,015XX N KILDARE AVE,0334,ATTEMPT ARMED - KNIFE / CUTTING INSTRUMENT,False,False,2534,26.0,23.0,03,1147424.0,1910122.0,2018,03/25/2020 03:45:43 PM,41.909336,-87.733867,"(41.909335675, -87.733867034)",1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,...,0,D25,ROBBERY,17:51,20180213,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.750428,13781,85.0,38.0,17.3,33.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [ ]:
data=data.drop(['Unnamed: 0',	'Unnamed: 0.1'	] ,1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.

In [ ]:
data.head()

,ID,Case Number,Date,Block,IUCR,Description,Arrest,Domestic,Beat,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,severe,Primary Type_ARSON,Primary Type_ASSAULT,Primary Type_BATTERY,Primary Type_BURGLARY,Primary Type_CONCEALED CARRY LICENSE VIOLATION,Primary Type_CRIM SEXUAL ASSAULT,Primary Type_CRIMINAL DAMAGE,Primary Type_CRIMINAL SEXUAL ASSAULT,Primary Type_CRIMINAL TRESPASS,Primary Type_DECEPTIVE PRACTICE,Primary Type_HOMICIDE,Primary Type_INTERFERENCE WITH PUBLIC OFFICER,Primary Type_INTIMIDATION,Primary Type_LIQUOR LAW VIOLATION,Primary Type_MOTOR VEHICLE THEFT,Primary Type_NARCOTICS,Primary Type_OFFENSE INVOLVING CHILDREN,Primary Type_PROSTITUTION,Primary Type_PUBLIC PEACE VIOLATION,Primary Type_ROBBERY,Primary Type_SEX OFFENSE,Primary Type_STALKING,Primary Type_THEFT,Primary Type_WEAPONS VIOLATION,District_D1,District_D10,District_D11,District_D12,District_D14,District_D15,...,District_D9,District,Primary Type,time_24hour,Date_no_time,Timeblock_0,Timeblock_12,Timeblock_15,Timeblock_18,Timeblock_21,Timeblock_3,Timeblock_6,Timeblock_9,Weekday_Friday,Weekday_Monday,Weekday_Saturday,Weekday_Sunday,Weekday_Thursday,Weekday_Tuesday,Weekday_Wednesday,closest_station,Income,HARDSHIP INDEX,Under18_over64,Unemployed,House_below_poverty,Location Description_ALLEY,Location Description_APARTMENT,Location Description_BAR OR TAVERN,Location Description_COMMERCIAL / BUSINESS OFFICE,Location Description_CONVENIENCE STORE,Location Description_CTA TRAIN,Location Description_DEPARTMENT STORE,Location Description_GAS STATION,Location Description_GROCERY FOOD STORE,Location Description_OTHER (SPECIFY),Location Description_PARKING LOT / GARAGE (NON RESIDENTIAL),Location Description_PARKING LOT/GARAGE(NON.RESID.),Location Description_RESIDENCE,Location Description_RESIDENCE - PORCH / HALLWAY,Location Description_RESIDENCE - YARD (FRONT / BACK),Location Description_RESIDENCE PORCH/HALLWAY,Location Description_RESIDENCE-GARAGE,Location Description_RESIDENTIAL YARD (FRONT/BACK),Location Description_RESTAURANT,"Location Description_SCHOOL, PUBLIC, BUILDING",Location Description_SIDEWALK,Location Description_SMALL RETAIL STORE,Location Description_STREET,Location Description_VEHICLE NON-COMMERCIAL
0,11458569,JB451615,09/25/2018 03:45:00 PM,068XX S WASHTENAW AVE,0560,SIMPLE,False,False,831,17.0,66.0,08A,1159554.0,1859215.0,2018,06/04/2019 04:01:14 PM,41.769400,-87.690706,"(41.769399886, -87.690705813)",1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,D8,ASSAULT,15:45,20180925,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.145603,13231,80.0,40.6,17.1,27.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,11492590,JB496541,10/30/2018 04:59:00 PM,040XX W 30TH ST,041A,AGGRAVATED: HANDGUN,True,False,1031,22.0,30.0,04B,1149760.0,1884400.0,2018,06/04/2019 04:01:14 PM,41.838706,-87.725954,"(41.838706452, -87.72595418)",1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,...,0,D10,BATTERY,16:59,20181030,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.535472,10402,96.0,33.8,15.8,30.7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,11514713,JB525811,11/23/2018 01:30:00 AM,059XX W IOWA ST,1753,SEX ASSLT OF CHILD BY FAM MBR,True,False,1511,29.0,25.0,02,1136588.0,1905390.0,2018,06/04/2019 04:01:14 PM,41.896551,-87.773788,"(41.896551396, -87.773787663)",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,...,0,D15,OFFENSE INVOLVING CHILDREN,01:30,20181123,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1.172747,15957,73.0,37.9,22.6,28.6,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,11203556,JB115393,01/13/2018 08:24:00 PM,017XX W COLUMBIA AVE,041A,AGGRAVATED - HANDGUN,False,False,2432,49.0,1.0,04B,1163373.0,1944877.0,2018,03/25/2020 03:45:43 PM,42.004384,-87.674296,"(42.004384227, -87.674295522)",1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,D24,BATTERY,20:24,20180113,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0.353593,23939,39.0,27.5,8.7,23.6,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,11230081,JB151031,02/13/2018 05:51:00 PM,015XX N KILDARE AVE,0334,ATTEMPT ARMED - KNIFE / CUTTING INSTRUMENT,False,False,2534,26.0,23.0,03,1147424.0,1910122.0,2018,03/25/2020 03:45:43 PM,41.909336,-87.733867,"(41.909335675, -87.733867034)",1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,...,0,D25,ROBBERY,17:51,20180213,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.750428,13781,85.0,38.0,17.3,33.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [ ]:
data.reset_index(inplace=True)
data.head(5)

,index,ID,Case Number,Date,Block,IUCR,Description,Arrest,Domestic,Beat,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,severe,Primary Type_ARSON,Primary Type_ASSAULT,Primary Type_BATTERY,Primary Type_BURGLARY,Primary Type_CONCEALED CARRY LICENSE VIOLATION,Primary Type_CRIM SEXUAL ASSAULT,Primary Type_CRIMINAL DAMAGE,Primary Type_CRIMINAL SEXUAL ASSAULT,Primary Type_CRIMINAL TRESPASS,Primary Type_DECEPTIVE PRACTICE,Primary Type_HOMICIDE,Primary Type_INTERFERENCE WITH PUBLIC OFFICER,Primary Type_INTIMIDATION,Primary Type_LIQUOR LAW VIOLATION,Primary Type_MOTOR VEHICLE THEFT,Primary Type_NARCOTICS,Primary Type_OFFENSE INVOLVING CHILDREN,Primary Type_PROSTITUTION,Primary Type_PUBLIC PEACE VIOLATION,Primary Type_ROBBERY,Primary Type_SEX OFFENSE,Primary Type_STALKING,Primary Type_THEFT,Primary Type_WEAPONS VIOLATION,District_D1,District_D10,District_D11,District_D12,District_D14,...,District_D9,District,Primary Type,time_24hour,Date_no_time,Timeblock_0,Timeblock_12,Timeblock_15,Timeblock_18,Timeblock_21,Timeblock_3,Timeblock_6,Timeblock_9,Weekday_Friday,Weekday_Monday,Weekday_Saturday,Weekday_Sunday,Weekday_Thursday,Weekday_Tuesday,Weekday_Wednesday,closest_station,Income,HARDSHIP INDEX,Under18_over64,Unemployed,House_below_poverty,Location Description_ALLEY,Location Description_APARTMENT,Location Description_BAR OR TAVERN,Location Description_COMMERCIAL / BUSINESS OFFICE,Location Description_CONVENIENCE STORE,Location Description_CTA TRAIN,Location Description_DEPARTMENT STORE,Location Description_GAS STATION,Location Description_GROCERY FOOD STORE,Location Description_OTHER (SPECIFY),Location Description_PARKING LOT / GARAGE (NON RESIDENTIAL),Location Description_PARKING LOT/GARAGE(NON.RESID.),Location Description_RESIDENCE,Location Description_RESIDENCE - PORCH / HALLWAY,Location Description_RESIDENCE - YARD (FRONT / BACK),Location Description_RESIDENCE PORCH/HALLWAY,Location Description_RESIDENCE-GARAGE,Location Description_RESIDENTIAL YARD (FRONT/BACK),Location Description_RESTAURANT,"Location Description_SCHOOL, PUBLIC, BUILDING",Location Description_SIDEWALK,Location Description_SMALL RETAIL STORE,Location Description_STREET,Location Description_VEHICLE NON-COMMERCIAL
0,0,11458569,JB451615,09/25/2018 03:45:00 PM,068XX S WASHTENAW AVE,0560,SIMPLE,False,False,831,17.0,66.0,08A,1159554.0,1859215.0,2018,06/04/2019 04:01:14 PM,41.769400,-87.690706,"(41.769399886, -87.690705813)",1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,D8,ASSAULT,15:45,20180925,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.145603,13231,80.0,40.6,17.1,27.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,1,11492590,JB496541,10/30/2018 04:59:00 PM,040XX W 30TH ST,041A,AGGRAVATED: HANDGUN,True,False,1031,22.0,30.0,04B,1149760.0,1884400.0,2018,06/04/2019 04:01:14 PM,41.838706,-87.725954,"(41.838706452, -87.72595418)",1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,...,0,D10,BATTERY,16:59,20181030,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.535472,10402,96.0,33.8,15.8,30.7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,2,11514713,JB525811,11/23/2018 01:30:00 AM,059XX W IOWA ST,1753,SEX ASSLT OF CHILD BY FAM MBR,True,False,1511,29.0,25.0,02,1136588.0,1905390.0,2018,06/04/2019 04:01:14 PM,41.896551,-87.773788,"(41.896551396, -87.773787663)",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,...,0,D15,OFFENSE INVOLVING CHILDREN,01:30,20181123,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1.172747,15957,73.0,37.9,22.6,28.6,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,3,11203556,JB115393,01/13/2018 08:24:00 PM,017XX W COLUMBIA AVE,041A,AGGRAVATED - HANDGUN,False,False,2432,49.0,1.0,04B,1163373.0,1944877.0,2018,03/25/2020 03:45:43 PM,42.004384,-87.674296,"(42.004384227, -87.674295522)",1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,D24,BATTERY,20:24,20180113,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0.353593,23939,39.0,27.5,8.7,23.6,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,4,11230081,JB151031,02/13/2018 05:51:00 PM,015XX N KILDARE AVE,0334,ATTEMPT ARMED - KNIFE / CUTTING INSTRUMENT,False,False,2534,26.0,23.0,03,1147424.0,1910122.0,2018,03/25/2020 03:45:43 PM,41.909336,-87.733867,"(41.909335675, -87.733867034)",1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,...,0,D25,ROBBERY,17:51,20180213,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.750428,13781,85.0,38.0,17.3,33.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [ ]:
data=data.drop(["index"], axis=1)
data.head(5)

,ID,Case Number,Date,Block,IUCR,Description,Arrest,Domestic,Beat,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,severe,Primary Type_ARSON,Primary Type_ASSAULT,Primary Type_BATTERY,Primary Type_BURGLARY,Primary Type_CONCEALED CARRY LICENSE VIOLATION,Primary Type_CRIM SEXUAL ASSAULT,Primary Type_CRIMINAL DAMAGE,Primary Type_CRIMINAL SEXUAL ASSAULT,Primary Type_CRIMINAL TRESPASS,Primary Type_DECEPTIVE PRACTICE,Primary Type_HOMICIDE,Primary Type_INTERFERENCE WITH PUBLIC OFFICER,Primary Type_INTIMIDATION,Primary Type_LIQUOR LAW VIOLATION,Primary Type_MOTOR VEHICLE THEFT,Primary Type_NARCOTICS,Primary Type_OFFENSE INVOLVING CHILDREN,Primary Type_PROSTITUTION,Primary Type_PUBLIC PEACE VIOLATION,Primary Type_ROBBERY,Primary Type_SEX OFFENSE,Primary Type_STALKING,Primary Type_THEFT,Primary Type_WEAPONS VIOLATION,District_D1,District_D10,District_D11,District_D12,District_D14,District_D15,...,District_D9,District,Primary Type,time_24hour,Date_no_time,Timeblock_0,Timeblock_12,Timeblock_15,Timeblock_18,Timeblock_21,Timeblock_3,Timeblock_6,Timeblock_9,Weekday_Friday,Weekday_Monday,Weekday_Saturday,Weekday_Sunday,Weekday_Thursday,Weekday_Tuesday,Weekday_Wednesday,closest_station,Income,HARDSHIP INDEX,Under18_over64,Unemployed,House_below_poverty,Location Description_ALLEY,Location Description_APARTMENT,Location Description_BAR OR TAVERN,Location Description_COMMERCIAL / BUSINESS OFFICE,Location Description_CONVENIENCE STORE,Location Description_CTA TRAIN,Location Description_DEPARTMENT STORE,Location Description_GAS STATION,Location Description_GROCERY FOOD STORE,Location Description_OTHER (SPECIFY),Location Description_PARKING LOT / GARAGE (NON RESIDENTIAL),Location Description_PARKING LOT/GARAGE(NON.RESID.),Location Description_RESIDENCE,Location Description_RESIDENCE - PORCH / HALLWAY,Location Description_RESIDENCE - YARD (FRONT / BACK),Location Description_RESIDENCE PORCH/HALLWAY,Location Description_RESIDENCE-GARAGE,Location Description_RESIDENTIAL YARD (FRONT/BACK),Location Description_RESTAURANT,"Location Description_SCHOOL, PUBLIC, BUILDING",Location Description_SIDEWALK,Location Description_SMALL RETAIL STORE,Location Description_STREET,Location Description_VEHICLE NON-COMMERCIAL
0,11458569,JB451615,09/25/2018 03:45:00 PM,068XX S WASHTENAW AVE,0560,SIMPLE,False,False,831,17.0,66.0,08A,1159554.0,1859215.0,2018,06/04/2019 04:01:14 PM,41.769400,-87.690706,"(41.769399886, -87.690705813)",1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,D8,ASSAULT,15:45,20180925,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.145603,13231,80.0,40.6,17.1,27.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,11492590,JB496541,10/30/2018 04:59:00 PM,040XX W 30TH ST,041A,AGGRAVATED: HANDGUN,True,False,1031,22.0,30.0,04B,1149760.0,1884400.0,2018,06/04/2019 04:01:14 PM,41.838706,-87.725954,"(41.838706452, -87.72595418)",1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,...,0,D10,BATTERY,16:59,20181030,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.535472,10402,96.0,33.8,15.8,30.7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,11514713,JB525811,11/23/2018 01:30:00 AM,059XX W IOWA ST,1753,SEX ASSLT OF CHILD BY FAM MBR,True,False,1511,29.0,25.0,02,1136588.0,1905390.0,2018,06/04/2019 04:01:14 PM,41.896551,-87.773788,"(41.896551396, -87.773787663)",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,...,0,D15,OFFENSE INVOLVING CHILDREN,01:30,20181123,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1.172747,15957,73.0,37.9,22.6,28.6,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,11203556,JB115393,01/13/2018 08:24:00 PM,017XX W COLUMBIA AVE,041A,AGGRAVATED - HANDGUN,False,False,2432,49.0,1.0,04B,1163373.0,1944877.0,2018,03/25/2020 03:45:43 PM,42.004384,-87.674296,"(42.004384227, -87.674295522)",1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,D24,BATTERY,20:24,20180113,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0.353593,23939,39.0,27.5,8.7,23.6,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,11230081,JB151031,02/13/2018 05:51:00 PM,015XX N KILDARE AVE,0334,ATTEMPT ARMED - KNIFE / CUTTING INSTRUMENT,False,False,2534,26.0,23.0,03,1147424.0,1910122.0,2018,03/25/2020 03:45:43 PM,41.909336,-87.733867,"(41.909335675, -87.733867034)",1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,...,0,D25,ROBBERY,17:51,20180213,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1.750428,13781,85.0,38.0,17.3,33.9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [ ]:
data=data.drop(["Date","Block","IUCR","Description","Ward","Community Area","FBI Code"], axis=1)
data=data.drop(["X Coordinate","Y Coordinate","Year","Location","District","Primary Type","time_24hour","Date_no_time"], axis=1)

In [ ]:
a=list(data.columns.values)
droplist=[]
for i in a:
    if i.startswith("Primary Type"):
        droplist.append(i)
data=data.drop(droplist, axis=1)

In [ ]:
from sklearn.model_selection import cross_validate

In [ ]:
from sklearn.model_selection import train_test_split
itrain, itest = train_test_split(range(data.shape[0]), train_size=0.7)

In [ ]:
import numpy as np 
import pandas as pd 

train_data = pd.read_csv("/content/drive/MyDrive/Project/Crime (18-p)/Crime - (18-p) 1_final/input/train.csv")

print(train_data.head())
print(train_data.shape)

In [ ]:
mask=np.ones(data.shape[0], dtype='int')
mask[itrain]=1
mask[itest]=0
mask=(mask==1)

In [ ]:
data=data.dropna()
np.nan_to_num(data)

array([['JB451615', False, False, ..., 0, 0, 0],
       ['JB496541', True, False, ..., 0, 0, 0],
       ['JB525811', True, False, ..., 0, 0, 0],
       ...,
       ['JF179791', False, True, ..., 0, 0, 0],
       ['JF179649', False, False, ..., 0, 0, 0],
       ['JF179224', False, False, ..., 0, 1, 0]], dtype=object)

In [ ]:
target = train_data["Primary Type "].unique()
print(target)

In [ ]:
test_data = pd.read_csv("/content/drive/MyDrive/Project/Crime (18-p)/Crime - (18-p) 1_final/input/test.csv")
print(test_data.head())
print(test_data.shape)

In [ ]:
data_dict = {}
count = 1
for data in target:
    data_dict[data] = count
    count+=1
train_data["Primary Type"] = train_data["Primary Type"].replace(data_dict)

#Replacing the day of weeks
data_week_dict = {
    "Monday": 1,
    "Tuesday":2,
    "Wednesday":3,
    "Thursday":4,
    "Friday":5,
    "Saturday":6,
    "Sunday":7
}
train_data["DayOfWeek"] = train_data["DayOfWeek"].replace(data_week_dict)
test_data["DayOfWeek"] = test_data["DayOfWeek"].replace(data_week_dict)
#District
district = train_data["Closest Station"].unique()
data_dict_district = {}
count = 1
for data in district:
    data_dict_district[data] = count
    count+=1 
train_data["Closest Station"] = train_data["Closest Station"].replace(data_dict_district)
test_data["Closest Station"] = test_data["Closest Station"].replace(data_dict_district)

In [ ]:
print(train_data.head())

In [ ]:
columns_train = train_data.columns
print(columns_train)
columns_test = test_data.columns
print(columns_test)

In [ ]:
print(train_data.describe())

In [ ]:
corr = train_data.corr()
print(corr["Primary Type"])

In [ ]:
features = ["Case Number", "Closest Station",  "Lattitude", "Longtitude"]
X_train = train_data[features]
y_train = train_data["Primary type"]
X_test = test_data[features]

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
predictions = knn.predict(X_test)

In [ ]:
from collections import OrderedDict
data_dict_new = OrderedDict(sorted(data_dict.items()))
print(data_dict)

In [ ]:
result_dataframe = pd.DataFrame({
    "Id": test_data["Id"]
})
for key,value in data_dict_new.items():
    result_dataframe[key] = 0
count = 0
for item in predictions:
    for key,value in data_dict.items():
        if(value == item):
            result_dataframe[key][count] = 1
    count+=1
result_dataframe.to_csv("submission_knn.csv", index=False)